/** ADIM 10.1 — demo keşfet / yakındakiler verisi (gerçek geo: useNearbyPlayers) */
import type { HeroDiscoveryPlayer, NearbyPlayer } from './types'
import { NEARBY_DEMO_LABEL } from './nearbyDemo'

export const HERO_DISCOVERY_DEMO_LABEL = NEARBY_DEMO_LABEL

const heroSocial = (
  lastGame: string,
  today = 'Bugün aktif',
  matches = '4 maç',
  mutuals = '5 ortak',
  voice = 'İng. açık',
) => ({ lastGame, today, matches, mutuals, voice })

export const heroDiscoveryQueue: HeroDiscoveryPlayer[] = [
  {
    id: 'zeynep',
    name: 'Zeynep',
    age: 21,
    gender: 'female',
    verified: true,
    isOnline: true,
    distance: '1.2 km',
    location: 'İstanbul, Türkiye',
    compatibility: 92,
    portraitPosition: '14% 38%',
    social: heroSocial('Son: Black Desert'),
    interests: ['FPS', 'MOBA', 'Gamer', 'E-Spor'],
    tags: [
      { label: 'FPS', icon: 'gamepad' },
      { label: 'Rekabetçi', icon: 'gamepad' },
      { label: 'Seviye', icon: 'trophy' },
    ],
  },
  {
    id: 'mert',
    name: 'Mert',
    age: 24,
    gender: 'male',
    isOnline: true,
    distance: '3.2 km',
    location: 'İstanbul, Türkiye',
    compatibility: 87,
    portraitPosition: '32% 56%',
    social: heroSocial('Son: XOX'),
    interests: ['Strateji', 'Indie', 'Gamer', 'Sohbet'],
    tags: [
      { label: 'Strateji', icon: 'gamepad' },
      { label: 'Seviye', icon: 'trophy' },
    ],
  },
  {
    id: 'damla',
    name: 'Damla',
    age: 20,
    gender: 'female',
    verified: true,
    isOnline: true,
    distance: '4.1 km',
    location: 'Kadıköy, İstanbul',
    compatibility: 84,
    portraitPosition: '54% 54%',
    social: heroSocial('Son: Block Duel'),
    interests: ['Sohbet', 'Indie', 'Gamer'],
    tags: [
      { label: 'Casual', icon: 'gamepad' },
      { label: 'Seviye', icon: 'trophy' },
    ],
  },
  {
    id: 'ali',
    name: 'Ali',
    age: 23,
    gender: 'male',
    isOnline: true,
    distance: '2.4 km',
    location: 'Beşiktaş, İstanbul',
    compatibility: 79,
    portraitPosition: '8% 58%',
    social: heroSocial('Son: 8 Top'),
    interests: ['Spor', 'FPS', 'Battle Royale'],
    tags: [
      { label: 'Multiplayer', icon: 'gamepad' },
      { label: 'Seviye', icon: 'trophy' },
    ],
  },
  {
    id: 'emir',
    name: 'Emir',
    age: 25,
    gender: 'male',
    isOnline: true,
    distance: '5.0 km',
    location: 'Üsküdar, İstanbul',
    compatibility: 76,
    portraitPosition: '80% 55%',
    social: heroSocial('Son: Puzzle Rush'),
    interests: ['E-Spor', 'MOBA', 'Strateji', 'Anime'],
    tags: [
      { label: 'Ranked', icon: 'gamepad' },
      { label: 'Seviye', icon: 'trophy' },
    ],
  },
]

export const heroPlayerMeta = {
  compatibility: 92,
  distance: '1.2 km',
  lastGame: 'Son: Black Desert',
  stats: ['Bugün aktif', '4 maç', '5 ortak arkadaş', 'İng. açık'],
}

export const heroPortraitPosition = '50% 12%'

export const nearbyPlayers: NearbyPlayer[] = [
  {
    id: 'ali',
    name: 'Ali',
    age: 23,
    level: 18,
    interests: ['FPS', 'Gamer', 'MOBA'],
    distance: '2.4 km',
    isOnline: true,
    gender: 'male',
    portraitPosition: '8% 58%',
    recentActivity: 'Az önce Block Duel oynadı',
  },
  {
    id: 'mert',
    name: 'Mert',
    age: 24,
    level: 24,
    interests: ['Strateji', 'Indie', 'Gamer'],
    distance: '3.2 km',
    isOnline: true,
    gender: 'male',
    portraitPosition: '32% 56%',
    recentActivity: 'Az önce çevrimiçi oldu',
  },
  {
    id: 'damla',
    name: 'Damla',
    age: 20,
    level: 31,
    interests: ['Sohbet', 'Indie', 'Gamer'],
    distance: '4.1 km',
    verified: true,
    isOnline: true,
    gender: 'female',
    portraitPosition: '54% 54%',
    recentActivity: 'Puzzle oynuyor',
  },
  {
    id: 'emir',
    name: 'Emir',
    age: 25,
    level: 14,
    interests: ['Spor', 'FPS', 'Battle Royale'],
    distance: '5.0 km',
    isOnline: true,
    gender: 'male',
    portraitPosition: '80% 55%',
    recentActivity: '8 Top maçında',
  },
  {
    id: 'ece',
    name: 'Ece',
    age: 22,
    level: 37,
    interests: ['E-Spor', 'MOBA', 'Anime'],
    distance: '1.8 km',
    verified: true,
    isOnline: true,
    gender: 'female',
    portraitPosition: '20% 42%',
    recentActivity: 'Az önce çevrimiçi oldu',
  },
  {
    id: 'azra',
    name: 'Azra',
    age: 19,
    level: 9,
    interests: ['Sohbet', 'Gamer'],
    distance: '2.9 km',
    isOnline: true,
    gender: 'female',
    portraitPosition: '45% 48%',
    recentActivity: 'Az önce çevrimiçi oldu',
  },
  {
    id: 'can',
    name: 'Can',
    age: 26,
    level: 28,
    interests: ['FPS', 'Strateji', 'Gamer'],
    distance: '3.6 km',
    isOnline: true,
    gender: 'male',
    portraitPosition: '68% 52%',
    recentActivity: 'Block Duel oynuyor',
  },
  {
    id: 'selin',
    name: 'Selin',
    age: 21,
    level: 16,
    interests: ['Indie', 'Sohbet'],
    distance: '4.4 km',
    verified: true,
    isOnline: false,
    gender: 'female',
    portraitPosition: '12% 62%',
    recentActivity: '15 dk önce aktifti',
  },
  {
    id: 'berk',
    name: 'Berk',
    age: 24,
    level: 42,
    interests: ['MOBA', 'E-Spor', 'FPS'],
    distance: '5.2 km',
    isOnline: true,
    gender: 'male',
    portraitPosition: '38% 60%',
    recentActivity: 'Lobiye davet gönderdi',
  },
  {
    id: 'ilayda',
    name: 'İlayda',
    age: 20,
    level: 11,
    interests: ['Sohbet', 'Indie', 'Gamer'],
    distance: '6.1 km',
    isOnline: true,
    gender: 'female',
    portraitPosition: '72% 44%',
    recentActivity: 'Yeni eşleşme isteği',
  },
]

export const nearbyListLiveCaption = {
  activePlayersLabel: '247 oyuncu aktif',
  waitLabel: '3 kişi seni bekliyor',
  ticker: ['Ece Block Duel oynuyor', 'Mert Puzzle oynuyor', 'Azra Block Duel oynuyor'],
  sectionEyebrow: 'Lobi şu an canlı · 18 davet aktif',
}

export const premiumUnlockBanner = {
  title: "Premium'a Geç",
  subtitle: 'Sınırsız eşleşme, rozetler ve öncelikli lobiler seni bekliyor.',
  perks: ['Sınırsız beğeni', 'Öncelikli eşleşme', 'Özel rozetler'],
  cta: "Premium'a Geç",
}
