import { BrowserRouter, Route, Routes } from 'react-router-dom'
import { GemBalanceProvider } from './features/currency/GemBalanceProvider'
import { NearbyLikesProvider } from './features/home/NearbyLikesProvider'
import { ProfileLevelProvider } from './features/profile/ProfileLevelProvider'
import { AppRoutes } from './navigation/AppRoutes'
import './styles/currency-ui.css'
import './styles/home-filters.css'
import './styles/home-hero-stack.css'
import './styles/home-hero-aaa.css'
import './styles/home-hero-actions.css'
import './styles/home-premium-unlock.css'
import './styles/home-nearby-sheet.css'
import './styles/home-nearby-likes.css'
import './styles/home-nearby-card-aaa.css'
import './styles/home-nearby-screen.css'
import './styles/notifications.css'
import './styles/home-ambient.css'
import './styles/brand-aaa.css'
import './styles/navbar-tray.css'
import './styles/home.css'
import './styles/games.css'
import './styles/game-portrait.css'
import './styles/game-duel-ambient.css'
import './styles/game-duel-video.css'
import './styles/xox-game.css'
import './styles/brick-break.css'
import './styles/bubble-shooter.css'
import './styles/block-duel.css'
import './styles/math-duel.css'
import './styles/color-match.css'
import './styles/neon-crush.css'
import './styles/dart-duel.css'
import './styles/snake-duel.css'
import './styles/pong-duel.css'
import './styles/reflex-duel.css'
import './styles/simon-duel.css'
import './styles/whack-duel.css'
import './styles/rhythm-duel.css'
import './styles/catch-duel.css'
import './styles/slice-duel.css'
import './styles/basket-duel.css'
import './styles/chess-duel.css'
import './styles/galaga-duel.css'
import './styles/asteroids-duel.css'
import './styles/missile-command-duel.css'
import './styles/centipede-duel.css'
import './styles/frogger-duel.css'
import './styles/pac-dot-duel.css'
import './styles/invaders-duel.css'
import './styles/dig-dug-duel.css'
import './styles/tempest-duel.css'
import './styles/breakout-duel.css'
import './styles/robotron-duel.css'
import './styles/joust-duel.css'
import './styles/burger-time-duel.css'
import './styles/donkey-kong-duel.css'
import './styles/qbert-duel.css'
import './styles/paperboy-duel.css'
import './styles/spy-hunter-duel.css'
import './styles/marble-madness-duel.css'
import './styles/defender-duel.css'
import './styles/berzerk-duel.css'
import './styles/1942-duel.css'
import './styles/gradius-duel.css'
import './styles/time-pilot-duel.css'
import './styles/gyruss-duel.css'
import './styles/outrun-duel.css'
import './styles/rad-racer-duel.css'
import './styles/enduro-duel.css'
import './styles/contra-duel.css'
import './styles/metal-slug-duel.css'
import './styles/punch-out-duel.css'
import './styles/kung-fu-duel.css'
import './styles/bomberman-duel.css'
import './styles/tron-duel.css'
import './styles/pengo-duel.css'
import './styles/lode-runner-duel.css'
import './styles/space-harrier-duel.css'
import './styles/memory-duel.css'
import './styles/stack-duel.css'
import './styles/match.css'
import './styles/match-ambient.css'
import './styles/match-screen.css'
import './styles/match-aaa.css'
import './styles/match-toast.css'
import './styles/chat-ambient.css'
import './styles/chat.css'
import './styles/message-ambient.css'
import './styles/message-screen.css'
import './styles/message-final.css'
import './styles/profile.css'
import './styles/profile-ambient.css'
import './styles/photo-lightbox.css'
import './styles/premium.css'
import './styles/premium-feature-icons.css'
import './styles/navigation.css'

function App() {
  return (
    <GemBalanceProvider>
      <ProfileLevelProvider>
        <NearbyLikesProvider>
          <BrowserRouter>
            <Routes>
              <Route path="*" element={<AppRoutes />} />
            </Routes>
          </BrowserRouter>
        </NearbyLikesProvider>
      </ProfileLevelProvider>
    </GemBalanceProvider>
  )
}

export default App
